### ISSUE TITLE
上传文件时，报错

### ISSUE THREAD

**Issue by douxin** [ifanrx/hydrogen-js-sdk#1]
在 chooseImage 之后，调用 uploadFile 会报错，报错信息如下：

```
thirdScriptError
Cannot read property 'replace' of undefined;at pages/add_page_basic/add_page_basic onAddLogoTap function;at api chooseImage success callback function
TypeError: Cannot read property 'replace' of undefined
    at Object.u [as format] (http://924940195.appservice.open.weixin.qq.com/libs/sdk-v1.0.5.js:1:31601)
    at Object.uploadFile (http://924940195.appservice.open.weixin.qq.com/libs/sdk-v1.0.5.js:1:23105)
    at success (http://924940195.appservice.open.weixin.qq.com/pages/add_page_basic/add_page_basic.js:95:23)
    at Object.success (http://924940195.appservice.open.weixin.qq.com/WAService.js:3:7587)
    at .<anonymous> (http://924940195.appservice.open.weixin.qq.com/WAService.js:4:20493)
    at .<anonymous> (http://924940195.appservice.open.weixin.qq.com/asdebug.js:1:15314)
    at http://924940195.appservice.open.weixin.qq.com/WAService.js:3:7587
```

这个报错，不仅是在小程序的编辑器里会出现，在实际设备上也依然有这个错（上传文件部分的代码已经按照文档上的直接拷贝过来的依然报错）；

代码如下：
```javascript
wx.chooseImage({
          count: 1,
          success: res => {
              console.log('choose image ==>', res);
              this.setData({
                  logoTmpPath: res.tempFilePaths[0]
              });
              let params = {};
              let tempFilePaths = res.tempFilePaths;
              params.filePath = tempFilePaths;
              wx.BaaS.uploadFile(params).then(ret => {
                  console.log('upload logo ==>', ret);
              }).catch(err => {
                  console.error('upload logo ==>', err);
              })
          }
      })
```

其中，wx.chooseImage 是可以正常得到文件路径的，res.tempFilePaths 的值如下：
```
['wxfile://tmp_924940195o6zAJs4ki4xY9Vb4e9qCHbxsXp-U482a55e8fcb97e266ea662bc352aa49e.jpg']
```

**Comment by douxin** [comment]
所以这个问题如何解决呢 ？

**Comment by heshiyou** [comment]
@douxin 这几天在赶几个重要特性，非常抱歉未及时回复。请邮件我 ernest@ifanr.com 你的 appID，我们将进行问题定位。感谢！

**Comment by heshiyou** [comment]
@douxin Hi, 问题已经修复，请下载最新 sdk 使用。其中一个原因是 wechat upload file 请求未携带 User Agent 头，被我们的安全防御 ban 掉了。很抱歉给你带来使用上的麻烦。
